### ISSUE TITLE
FRC Now Support + Privacy Policy URL point to TBA

### ISSUE THREAD

**Issue by ZachOrr** [YonathanZetune/TheBlueAllianceFlutter#1]
Hey @YonathanZetune - it appears your support URL and privacy policy URL in the App Store both point to The Blue Alliance https://itunes.apple.com/us/app/frc-now/id1447059514

Our privacy policy/website don't relate to your app. Would you mind changing these to point them to more appropriate locations?

**Comment by YonathanZetune** [comment]
@ZachOrr No problem! I submitted a new binary and it should be updated in the next couple of days. Thank you for pointing this out.

**Comment by ZachOrr** [comment]
Wanted to follow up on this, since it seems like this hasn't been resolved yet.
